### PR TITLE
set up arbitrary customElements for posts

### PR DESCRIPTION
**Pull request by acrimer**
This PR would merge in the ability to add custom elements, like media, as allowed by node-rss version 1.1.0 (see more [here](https://github.com/dylang/node-rss/issues/19)). This is useful for making podcasts and adding in thumbnails or images to post content.

### CODE REVIEW

**Comment by hurrymaplelad** [comment]
Looks great!  Thanks for adding tests.  Mind adding the new option to the README?

**Comment by acrimer** [comment]
Done—hopefully that's sufficient!

**Comment by hurrymaplelad** [comment]
Perfect, thanks!

**Comment by hurrymaplelad** [comment]
Publised as v0.2.0

**Pull request merged**
