### PR TITLE
Add optional preprocessor function for feed entries

### PR DESCRIPTION
**Pull request by fhemberger**
I came across the situation where metalsmith files were totally okay for HTML, but invalid for XML/RSS feeds. I added a `preprocessor` function, which allows metalsmith fields to be remapped or content to be filtered before adding to the RSS feed.

### CODE REVIEW

**Comment by fhemberger** [comment]
@hurrymaplelad *bump* ;)

**Comment by hurrymaplelad** [comment]
Love it!

Just needs a brief description in the Readme and a basic test to merge.

When those are in I'll release an additive minor version, and remove `postDescription` and  `postCustomElements` in favor of `preprocessor` with the next major version.

**Comment by fhemberger** [comment]
Sure, I'll send an update.

**Comment by fhemberger** [comment]
@hurrymaplelad Sorry it took me so long to update this PR. Finally added a test and a description.

**Comment by hurrymaplelad** [comment]
Thanks!

**Comment by hurrymaplelad** [comment]
Published as `metalsmith-feed@0.4.0`

**Pull request merged**
